/* ═══════════════════════════════════════════════════════════════════════
   Keizaal Alchemy — ingredient & recipe catalog
   Extracted from alchemy-app.html so the app file stays small to edit.
   Loaded via <script src="alchemy-catalog.js"> BEFORE the app script, which
   reads it as window.ALCHEMY_CATALOG (aliased back to INGREDIENTS/RECIPES).

   KzlCraftingAlchemy is a FIXED recipe book, extracted from
   keizaal_recipes_test.csv. INGREDIENTS carries per-ingredient price/stock
   which the app fills in and persists; RECIPES is read-only.
   ═══════════════════════════════════════════════════════════════════════ */
window.ALCHEMY_CATALOG = (function(){
const INGREDIENTS = [
  {"name": "Amethyst", "type": "MISC", "price": 60, "stock": 2, "craft": true},
  {"name": "Bear Claws", "type": "INGR", "price": 4, "stock": 23, "craft": false},
  {"name": "Bleeding Crown", "type": "INGR", "price": 8, "stock": 14, "craft": false},
  {"name": "Blue Mountain Flower", "type": "INGR", "price": 2, "stock": 35, "craft": false},
  {"name": "Canis Root", "type": "INGR", "price": 4, "stock": 23, "craft": false},
  {"name": "Chaurus Eggs", "type": "INGR", "price": 8, "stock": 14, "craft": false},
  {"name": "Creep Cluster", "type": "INGR", "price": 4, "stock": 23, "craft": false},
  {"name": "Deathbell", "type": "INGR", "price": 12, "stock": 10, "craft": false},
  {"name": "Dragon's Tongue", "type": "INGR", "price": 8, "stock": 14, "craft": false},
  {"name": "Ectoplasm", "type": "INGR", "price": 12, "stock": 10, "craft": false},
  {"name": "Elves Ear", "type": "INGR", "price": 3, "stock": 28, "craft": false},
  {"name": "Eye of Sabre Cat", "type": "INGR", "price": 3, "stock": 28, "craft": false},
  {"name": "Fly Amanita", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Frost Mirriam", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Garlic", "type": "INGR", "price": 2, "stock": 35, "craft": false},
  {"name": "Giant Lichen", "type": "INGR", "price": 4, "stock": 23, "craft": false},
  {"name": "Glowing Mushroom", "type": "INGR", "price": 6, "stock": 18, "craft": false},
  {"name": "Grass Pod", "type": "INGR", "price": 3, "stock": 28, "craft": false},
  {"name": "Honey", "type": "ALCH", "price": 4, "stock": 23, "craft": false},
  {"name": "Honeycomb", "type": "INGR", "price": 6, "stock": 18, "craft": false},
  {"name": "Imp Stool", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Jazbay Grapes", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Jug of Milk", "type": "ALCH", "price": 3, "stock": 28, "craft": false},
  {"name": "Juniper Berries", "type": "INGR", "price": 3, "stock": 28, "craft": false},
  {"name": "Lavender", "type": "INGR", "price": 3, "stock": 28, "craft": false},
  {"name": "Moon Sugar", "type": "INGR", "price": 20, "stock": 6, "craft": false},
  {"name": "Mora Tapinella", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Nightshade", "type": "INGR", "price": 8, "stock": 14, "craft": false},
  {"name": "Petty Soul Gem", "type": "SLGM", "price": 15, "stock": 8, "craft": false},
  {"name": "Purple Mountain Flower", "type": "INGR", "price": 2, "stock": 35, "craft": false},
  {"name": "Red Mountain Flower", "type": "INGR", "price": 2, "stock": 35, "craft": false},
  {"name": "Rock Warbler Egg", "type": "INGR", "price": 4, "stock": 23, "craft": false},
  {"name": "Ruby", "type": "MISC", "price": 100, "stock": 2, "craft": false},
  {"name": "Salt Pile", "type": "INGR", "price": 2, "stock": 35, "craft": false},
  {"name": "Sapphire", "type": "MISC", "price": 90, "stock": 2, "craft": false},
  {"name": "Scaly Pholiota", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Slaughterfish Egg", "type": "INGR", "price": 5, "stock": 20, "craft": false},
  {"name": "Snowberries", "type": "INGR", "price": 4, "stock": 23, "craft": false},
  {"name": "Thistle Branch", "type": "INGR", "price": 2, "stock": 35, "craft": false},
  {"name": "Troll Fat", "type": "INGR", "price": 10, "stock": 12, "craft": false},
  {"name": "Tundra Cotton", "type": "INGR", "price": 3, "stock": 28, "craft": false},
  {"name": "Void Salts", "type": "INGR", "price": 55, "stock": 2, "craft": true},
  {"name": "Wheat", "type": "INGR", "price": 2, "stock": 35, "craft": false},
];
const RECIPES = [
  {"id": "KzlPot_UGCStallion", "name": "Stallion's Elixir", "cat": "Special", "kind": "potion", "tier": "", "tr": 0, "out": 1, "lines": [["Salt Pile", 1], ["Purple Mountain Flower", 10], ["Honeycomb", 4]]},
  {"id": "RestoreHealth01", "name": "Potion of Minor Healing", "cat": "Restore Health", "kind": "potion", "tier": "Minor", "tr": 1, "out": 1, "lines": [["Wheat", 7], ["Blue Mountain Flower", 15]]},
  {"id": "RestoreHealth02", "name": "Potion of Healing", "cat": "Restore Health", "kind": "potion", "tier": "Standard", "tr": 2, "out": 1, "lines": [["Wheat", 7], ["Imp Stool", 8], ["Blue Mountain Flower", 10]]},
  {"id": "RestoreHealth03", "name": "Potion of Plentiful Healing", "cat": "Restore Health", "kind": "potion", "tier": "Plentiful", "tr": 3, "out": 1, "lines": [["Wheat", 7], ["Imp Stool", 8], ["Eye of Sabre Cat", 2], ["Blue Mountain Flower", 10]]},
  {"id": "RestoreMagicka01", "name": "Potion of Minor Magicka", "cat": "Restore Magicka", "kind": "potion", "tier": "Minor", "tr": 1, "out": 1, "lines": [["Elves Ear", 12], ["Giant Lichen", 10]]},
  {"id": "RestoreMagicka02", "name": "Potion of Magicka", "cat": "Restore Magicka", "kind": "potion", "tier": "Standard", "tr": 2, "out": 1, "lines": [["Elves Ear", 12], ["Giant Lichen", 10], ["Creep Cluster", 8]]},
  {"id": "RestoreMagicka03", "name": "Potion of Plentiful Magicka", "cat": "Restore Magicka", "kind": "potion", "tier": "Plentiful", "tr": 3, "out": 1, "lines": [["Elves Ear", 12], ["Giant Lichen", 8], ["Creep Cluster", 8], ["Mora Tapinella", 12]]},
  {"id": "RestoreStamina01", "name": "Potion of Minor Stamina", "cat": "Restore Stamina", "kind": "potion", "tier": "Minor", "tr": 1, "out": 1, "lines": [["Purple Mountain Flower", 10], ["Honeycomb", 4]]},
  {"id": "RestoreStamina02", "name": "Potion of Stamina", "cat": "Restore Stamina", "kind": "potion", "tier": "Standard", "tr": 2, "out": 1, "lines": [["Juniper Berries", 8], ["Purple Mountain Flower", 12], ["Honeycomb", 6]]},
  {"id": "RestoreStamina03", "name": "Potion of Plentiful Stamina", "cat": "Restore Stamina", "kind": "potion", "tier": "Plentiful", "tr": 3, "out": 1, "lines": [["Juniper Berries", 5], ["Bear Claws", 2], ["Purple Mountain Flower", 10], ["Honeycomb", 4]]},
  {"id": "FortifyMagicka01", "name": "Potion of Extra Magicka", "cat": "Fortify Magicka", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Void Salts", 3], ["Tundra Cotton", 10]]},
  {"id": "FortifyMagicka02", "name": "Draught of Extra Magicka", "cat": "Fortify Magicka", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Void Salts", 3], ["Ectoplasm", 2], ["Tundra Cotton", 10]]},
  {"id": "FortifyMagickaRate01", "name": "Potion of Lasting Potency", "cat": "Fortify Magicka Regen", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Salt Pile", 5], ["Garlic", 15]]},
  {"id": "FortifyMagickaRate02", "name": "Draught of Lasting Potency", "cat": "Fortify Magicka Regen", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Salt Pile", 5], ["Garlic", 15], ["Moon Sugar", 2]]},
  {"id": "FortifyStaminaRate02", "name": "Draught of Vigor", "cat": "Fortify Stamina Regen", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Thistle Branch", 10], ["Fly Amanita", 8], ["Scaly Pholiota", 8]]},
  {"id": "FortifyStaminaRate01", "name": "Potion of Vigor", "cat": "Fortify Stamina Regen", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Fly Amanita", 8], ["Scaly Pholiota", 8]]},
  {"id": "FortifyStamina01", "name": "Potion of Enhanced Stamina", "cat": "Fortify Stamina", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Garlic", 8], ["Lavender", 12]]},
  {"id": "FortifyStamina02", "name": "Draught of Enhanced Stamina", "cat": "Fortify Stamina", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Garlic", 8], ["Chaurus Eggs", 4], ["Lavender", 12]]},
  {"id": "FoodWineBottle02", "name": "Wine", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Frost Mirriam", 3], ["Jazbay Grapes", 8]]},
  {"id": "KzlSkooma", "name": "Skooma", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Nightshade", 10], ["Moon Sugar", 5]]},
  {"id": "Ale", "name": "Ale", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Lavender", 2], ["Wheat", 5]]},
  {"id": "FortifySkillDestruction01", "name": "Potion of Destruction", "cat": "Fortify Destruction", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Glowing Mushroom", 8], ["Honeycomb", 6]]},
  {"id": "FortifySkillDestruction02", "name": "Draught of Destruction", "cat": "Fortify Destruction", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Ectoplasm", 2], ["Glowing Mushroom", 8], ["Honeycomb", 6]]},
  {"id": "FortifySkillOneHanded01", "name": "Potion of the Warrior", "cat": "Fortify One-Handed", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Canis Root", 8], ["Rock Warbler Egg", 6]]},
  {"id": "FortifySkillOneHanded02", "name": "Draught of the Warrior", "cat": "Fortify One-Handed", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Canis Root", 8], ["Bear Claws", 2], ["Rock Warbler Egg", 4]]},
  {"id": "FortifySkillTwoHanded01", "name": "Potion of the Berserker", "cat": "Fortify Two-Handed", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Fly Amanita", 12], ["Dragon's Tongue", 8]]},
  {"id": "FortifySkillTwoHanded02", "name": "Draught of the Berserker", "cat": "Fortify Two-Handed", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Troll Fat", 2], ["Fly Amanita", 8], ["Dragon's Tongue", 12]]},
  {"id": "FortifySkillRestoration01", "name": "Potion of the Healer", "cat": "Fortify Restoration", "kind": "potion", "tier": "Potion", "tr": 1, "out": 1, "lines": [["Salt Pile", 5], ["Red Mountain Flower", 15]]},
  {"id": "FortifySkillRestoration02", "name": "Draught of the Healer", "cat": "Fortify Restoration", "kind": "potion", "tier": "Draught", "tr": 2, "out": 1, "lines": [["Salt Pile", 5], ["Juniper Berries", 8], ["Red Mountain Flower", 15]]},
  {"id": "ResistMagic25", "name": "Potion of Resist Magic", "cat": "Resist Magic", "kind": "potion", "tier": "25%", "tr": 1, "out": 1, "lines": [["Tundra Cotton", 10], ["Bleeding Crown", 8]]},
  {"id": "ResistMagic50", "name": "Draught of Resist Magic", "cat": "Resist Magic", "kind": "potion", "tier": "50%", "tr": 2, "out": 1, "lines": [["Void Salts", 3], ["Tundra Cotton", 10], ["Bleeding Crown", 8]]},
  {"id": "FoodMead", "name": "Nord Mead", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Snowberries", 2], ["Honey", 5]]},
  {"id": "FirebrandWine", "name": "Firebrand Wine", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Elves Ear", 2], ["Jazbay Grapes", 8], ["Dragon's Tongue", 4]]},
  {"id": "FavorSorexRum", "name": "Stros M'Kai Rum", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Elves Ear", 8], ["Deathbell", 5], ["Canis Root", 2]]},
  {"id": "FoodHonningbrewMead", "name": "Honningbrew Mead", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Snowberries", 2], ["Lavender", 6], ["Honey", 5]]},
  {"id": "VoidSalts", "name": "Void Salts", "cat": "Reagent", "kind": "reagent", "tier": "", "tr": 0, "out": 1, "lines": [["Petty Soul Gem", 1], ["Salt Pile", 2], ["Amethyst", 2]]},
  {"id": "FireSalts", "name": "Fire Salts", "cat": "Reagent", "kind": "reagent", "tier": "", "tr": 0, "out": 1, "lines": [["Petty Soul Gem", 1], ["Salt Pile", 2], ["Ruby", 2]]},
  {"id": "FrostSalts", "name": "Frost Salts", "cat": "Reagent", "kind": "reagent", "tier": "", "tr": 0, "out": 1, "lines": [["Petty Soul Gem", 1], ["Salt Pile", 2], ["Sapphire", 2]]},
  {"id": "FoodBlackBriarMead", "name": "Black-Briar Mead", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Thistle Branch", 5], ["Snowberries", 2], ["Honey", 5]]},
  {"id": "FoodSolitudeSpicedWine", "name": "Bashkh's Mulled Wine", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Snowberries", 4], ["Jazbay Grapes", 6], ["Dragon's Tongue", 3]]},
  {"id": "DLC2FoodAshfireMead", "name": "Ashfire Mead", "cat": "Food & Drink", "kind": "food", "tier": "", "tr": 0, "out": 1, "lines": [["Snowberries", 3], ["Salt Pile", 4], ["Honey", 4]]},
  {"id": "KzlPot_UGCBathwater", "name": "Dibella's Holy Bathwater", "cat": "Special", "kind": "potion", "tier": "", "tr": 0, "out": 1, "lines": [["Salt Pile", 1], ["Wheat", 5], ["Blue Mountain Flower", 12]]},
  {"id": "KzlPot_UGCMagMilk", "name": "Farmer's Magical Milk", "cat": "Special", "kind": "potion", "tier": "", "tr": 0, "out": 1, "lines": [["Elves Ear", 10], ["Giant Lichen", 8], ["Jug of Milk", 1]]},
  {"id": "KzlPot_FeatherFeet", "name": "Feather Foot Tonic", "cat": "Special", "kind": "potion", "tier": "", "tr": 0, "out": 1, "lines": [["Wheat", 10], ["Red Mountain Flower", 10], ["Creep Cluster", 6]]},
  {"id": "CureDisease", "name": "Potion of Cure Disease", "cat": "Cure Disease", "kind": "potion", "tier": "", "tr": 0, "out": 1, "lines": [["Garlic", 3], ["Slaughterfish Egg", 5], ["Grass Pod", 7]]},
  {"id": "GemAmethyst", "name": "Amethyst", "cat": "Reagent", "kind": "reagent", "tier": "", "tr": 0, "out": 1, "lines": [["Ruby", 1], ["Sapphire", 1]]},
];
  return { INGREDIENTS, RECIPES };
})();
