/* ═══════════════════════════════════════════════════════════════════════
   Keizaal Tailor — crafting catalog (materials / intermediates / recipes)
   Extracted from tailor-app.html so the app file stays small to edit.
   Loaded via <script src="tailor-catalog.js"> BEFORE the app script, which
   reads it as window.TAILOR_CATALOG.

   Source: the Keizaal mod via the recipe-extraction pipeline
   (xEdit COBJ winning-override -> CSV -> converter). Prices/values are
   left blank; each user fills their own. Every recipe carries a src: tag.
   ═══════════════════════════════════════════════════════════════════════ */
window.TAILOR_CATALOG = (function(){
  const uid = () => Math.random().toString(36).slice(2,9);
  const L = (ingredient, qty) => ({ ingredient, qty });
  return {
  materials: [
    { id:uid(), name:"Bear Pelt", price:0, stock:0 },
    { id:uid(), name:"Corundum Ore", price:0, stock:0 },
    { id:uid(), name:"Firewood", price:0, stock:0 },
    { id:uid(), name:"Gold Ore", price:0, stock:0 },
    { id:uid(), name:"Iron Ore", price:0, stock:0 },
    { id:uid(), name:"Leather", price:0, stock:0 },
    { id:uid(), name:"Lesser Soul Gem", price:0, stock:0 },
    { id:uid(), name:"Linen Wrap", price:0, stock:0 },
    { id:uid(), name:"Quicksilver Ore", price:0, stock:0 },
    { id:uid(), name:"Sabre Cat Pelt", price:0, stock:0 },
    { id:uid(), name:"Sabre Cat Snow Pelt", price:0, stock:0 },
    { id:uid(), name:"Sabre Cat Tooth", price:0, stock:0 },
    { id:uid(), name:"Silver Ore", price:0, stock:0 },
    { id:uid(), name:"Snow Bear Pelt", price:0, stock:0 },
    { id:uid(), name:"Tundra Cotton", price:0, stock:0 },
    { id:uid(), name:"Vale Sabre Cat Hide", price:0, stock:0 },
    { id:uid(), name:"Yellow Mountain Flower", price:0, stock:0 },
  ],
  intermediates: [
    { id:uid(), name:"Charcoal", yield:1, labor:0, stock:0, lines:[ L("Firewood",4) ] },
    { id:uid(), name:"Coke", yield:1, labor:0, stock:0, lines:[ L("Firewood",12) ] },
    { id:uid(), name:"Corundum Ingot", yield:1, labor:0, stock:0, lines:[ L("Corundum Ore",8), L("Poor Charcoal",8) ] },
    { id:uid(), name:"Gold Ingot", yield:1, labor:0, stock:0, lines:[ L("Gold Ore",6), L("Charcoal",6) ] },
    { id:uid(), name:"Iron Ingot", yield:1, labor:0, stock:0, lines:[ L("Iron Ore",6), L("Poor Charcoal",6) ] },
    { id:uid(), name:"Leather Strips", yield:4, labor:0, stock:0, lines:[ L("Leather",1) ] },
    { id:uid(), name:"Poor Charcoal", yield:1, labor:0, stock:0, lines:[ L("Firewood",2) ] },
    { id:uid(), name:"Quicksilver Ingot", yield:1, labor:0, stock:0, lines:[ L("Quicksilver Ore",6), L("Coke",6) ] },
    { id:uid(), name:"Silver Ingot", yield:1, labor:0, stock:0, lines:[ L("Silver Ore",6), L("Charcoal",6) ] },
    { id:uid(), name:"Thread", yield:1, labor:0, stock:0, lines:[ L("Yellow Mountain Flower",5) ] },
  ],
  recipes: [
    { id:uid(), name:"Adept Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Adept Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather Strips",1), L("Thread",4) ] },
    { id:uid(), name:"Alik'r Hood", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",3) ] },
    { id:uid(), name:"Apprentice Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Archmage's Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",2) ] },
    { id:uid(), name:"Archmage's Hood", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",3) ] },
    { id:uid(), name:"Archmage's Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Arkay Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Azura Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Belted Tunic", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Black Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Black Priest Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Black Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Blacksmith's Apron", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",3) ] },
    { id:uid(), name:"Blue Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Blue Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Boy's Blue Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Boy's Green Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Boy's Grey Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Boy's Red Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Boy's Yellow Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Brown Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Brown Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Chef's Hat", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Chef's Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"College Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",4), L("Thread",6) ] },
    { id:uid(), name:"College of Winterhold Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Common Clothes 01", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 02", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 03", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 04", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 05", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 06", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 07", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 08", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 09", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 10", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 11", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 12", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 13", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 14", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 15", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 16", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 17", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 18", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 19", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 20", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 21", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 22", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 23", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 24", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 25", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 26", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 27", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 28", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 29", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 30", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 31", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 32", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 33", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 34", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 35", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 36", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 37", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 38", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 39", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 40", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 41", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Clothes 42", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",1), L("Leather",1) ] },
    { id:uid(), name:"Common Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Common Robes 03", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 05", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 06", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 07", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 08", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 09", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 12", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 14", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 15", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 16", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 17", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 20", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 21", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes 22", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 01", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 02", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 04", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 10", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 11", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 13", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Common Robes Hooded 18", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather",2) ] },
    { id:uid(), name:"Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Cuffed Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",3) ] },
    { id:uid(), name:"Cultist Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Cultist Gloves", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Cultist Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"Daedric Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Dark Alik'r Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",3) ] },
    { id:uid(), name:"Dark Brotherhood Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Dark Hammerfell Garb", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"Dark Redguard Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Dawngaurd Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Dibella Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Divines Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Dunmer Hooded Outfit", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Dunmer Outfit", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Dunmer Shoes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Embellished Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Embroidered Garment", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Emperor's Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Expert Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather Strips",1), L("Thread",4) ] },
    { id:uid(), name:"Exquisite Cloak", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Quicksilver Ingot",2), L("Thread",10) ] },
    { id:uid(), name:"Falkreath Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Fastened Scarf", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",10) ] },
    { id:uid(), name:"Fine Armguards", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather Strips",2), L("Leather",2) ] },
    { id:uid(), name:"Fine Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",3) ] },
    { id:uid(), name:"Fine Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Fine Clothes Arcana", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Aureate Death", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Bardic", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Blood Moon", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Blood Pact", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Blue Moon", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Burnished", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Charcoal", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Darkmoon", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Deepwood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Fuscia", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Ilinalta", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Poison Ivy", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Red Violet", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Seashell", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Spring Pink", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Ulvenwald", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Violet Kiss", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Clothes Wolfsbane", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Silver Ingot",2), L("Gold Ingot",2), L("Leather",2), L("Thread",16) ] },
    { id:uid(), name:"Fine Hat", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Fine Raiment", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Footwraps", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1) ] },
    { id:uid(), name:"Fur Cloak (Black)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Bear Pelt",1), L("Gold Ingot",1) ] },
    { id:uid(), name:"Fur Cloak (Brown)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Sabre Cat Pelt",1), L("Gold Ingot",1) ] },
    { id:uid(), name:"Fur Cloak (Snowy Sabre)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Sabre Cat Snow Pelt",1), L("Gold Ingot",1) ] },
    { id:uid(), name:"Fur Cloak (Vale Sabre)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Gold Ingot",1), L("Vale Sabre Cat Hide",1) ] },
    { id:uid(), name:"Fur Cloak (White)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Snow Bear Pelt",1), L("Gold Ingot",1) ] },
    { id:uid(), name:"Fur-Trimmed Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Fur-lined Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",3) ] },
    { id:uid(), name:"Gathered Scarf", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",1), L("Thread",10) ] },
    { id:uid(), name:"Gilded Wristguards", value:null, labor:null, demand:1, src:"mod", lines:[ L("Gold Ingot",1), L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Girl's Blue Dress", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Girl's Green Dress", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Girl's Grey Dress", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Girl's Red Dress", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Girl's Yellow Dress", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Gloves", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Glowdust Gem Backpack", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Lesser Soul Gem",1), L("Gold Ingot",1), L("Leather Strips",2), L("Leather",2) ] },
    { id:uid(), name:"Green Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Green Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Grey Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Grey Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Greybeard's Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Greybeard's Hood", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Greybeard's Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hammerfell Garb", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"Hat", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Heavy Quilted Surcoat 01", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Hjaalmarch Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Hooded Archmage's Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Hooded Arkay Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Azura Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Black Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Blue Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Brown Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Dibella Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Divines Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Green Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Grey Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Julianos Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Kynareth Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Mara Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Monk Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Monk Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Necromancer Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Red Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Talos Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Hooded Thalmor Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"Jester's Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Jester's Clothes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Jester's Gloves", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Jester's Hat", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Julianos Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Kynareth Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Leather", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Sabre Cat Snow Pelt",4) ] },
    { id:uid(), name:"Leather Cape", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2) ] },
    { id:uid(), name:"Linen Cape (Black)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Linen Cape (Blue)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Linen Cape (Green)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Linen Cape (Purple)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Linen Cape (Red)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Linen Cape (White)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Linen Cape (Yellow)", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Loose Neck Gaiter", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather Strips",2), L("Thread",10) ] },
    { id:uid(), name:"Mage Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2) ] },
    { id:uid(), name:"Mage Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Mage Robes Variant", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Mara Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Markarth Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Master Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather Strips",1), L("Thread",4) ] },
    { id:uid(), name:"Miner's Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Monk Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Monk Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Monk Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Moth Priest Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Moth Priest Sandals", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Mourner's Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Mourner's Hat", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Mythic Dawn Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Mythic Dawn Gloves", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Mythic Dawn Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Mythic Dawn Hooded Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Mythic Dawn Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Necromancer Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Necromancer Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Noble Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Novice Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Novice Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather Strips",1), L("Thread",4) ] },
    { id:uid(), name:"Orange Mage Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Pale Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Patchwork Satchel", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",10) ] },
    { id:uid(), name:"Pleated Shoes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",3) ] },
    { id:uid(), name:"Priest Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",3) ] },
    { id:uid(), name:"Priest Sandals", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",2) ] },
    { id:uid(), name:"Prisoner's Cuffs", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1) ] },
    { id:uid(), name:"Psijic Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",2) ] },
    { id:uid(), name:"Psijic Gloves", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",2) ] },
    { id:uid(), name:"Psijic Hood", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",3) ] },
    { id:uid(), name:"Psijic Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Quilted Mantle", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",1), L("Leather Strips",2), L("Thread",10) ] },
    { id:uid(), name:"Quilted Surcoat 01", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Quilted Surcoat 02", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Quilted Tunic", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Quilted Tunic and Green Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Quilted Tunic and White Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Quilted Tunic with Surcoat", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",12), L("Leather",2) ] },
    { id:uid(), name:"Ragged Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1) ] },
    { id:uid(), name:"Ragged Cap", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1) ] },
    { id:uid(), name:"Ragged Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1) ] },
    { id:uid(), name:"Ragged Trousers", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1) ] },
    { id:uid(), name:"Red Cowl", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Red Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Redguard Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Refined Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Reinforced Backpack", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Corundum Ingot",1), L("Leather Strips",3), L("Leather",2), L("Thread",10) ] },
    { id:uid(), name:"Reinforced Backpack & Lantern", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",2), L("Corundum Ingot",1), L("Firewood",2), L("Leather Strips",4), L("Leather",3) ] },
    { id:uid(), name:"Reinforced Mantle", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",1), L("Leather Strips",2), L("Thread",10) ] },
    { id:uid(), name:"Reinforced Satchel", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Quicksilver Ingot",1), L("Leather Strips",3), L("Leather",2) ] },
    { id:uid(), name:"Riften Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Roughspun Tunic", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1) ] },
    { id:uid(), name:"Rugged Cape", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",10) ] },
    { id:uid(), name:"Rugged Mask", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Shoes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Short Cloth Cape", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",1), L("Thread",10) ] },
    { id:uid(), name:"Short Woven Scarf", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",10) ] },
    { id:uid(), name:"Shrouded Hand Wraps", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Shrouded Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Shrouded Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Shrouded Shoes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Solitude Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Stormcloak Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Sturdy Pouch (Left)", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Quicksilver Ingot",1), L("Leather Strips",1), L("Thread",5) ] },
    { id:uid(), name:"Sturdy Pouch (Right)", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Quicksilver Ingot",1), L("Leather Strips",1), L("Thread",5) ] },
    { id:uid(), name:"Talos Robes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Tavern Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Telvanni Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"Telvanni Shoes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Temple Priest Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Temple Priest Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",3) ] },
    { id:uid(), name:"Temple Priest Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Thalmor Gloves", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",2), L("Thread",1) ] },
    { id:uid(), name:"Thalmor Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",3) ] },
    { id:uid(), name:"Thalmor Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",4) ] },
    { id:uid(), name:"Tied Linen Pouch (Left)", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",10) ] },
    { id:uid(), name:"Tied Linen Pouch (Right)", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",10) ] },
    { id:uid(), name:"Toothlock Satchel", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Sabre Cat Tooth",1), L("Leather Strips",2), L("Thread",5) ] },
    { id:uid(), name:"Trader's Resource", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",2), L("Firewood",2), L("Leather Strips",4), L("Thread",5) ] },
    { id:uid(), name:"Trader's Resource & Lantern", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Iron Ingot",4), L("Firewood",3), L("Leather Strips",4), L("Thread",5) ] },
    { id:uid(), name:"Traveller Robes Black", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Black Hooded", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Brown", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",1) ] },
    { id:uid(), name:"Traveller Robes Brown Hooded", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Grey", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Grey Hooded", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Red", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Red Hooded", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Tan", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",3) ] },
    { id:uid(), name:"Traveller Robes Tan Hooded", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Tundra Cotton",5), L("Leather Strips",2) ] },
    { id:uid(), name:"Ulfric's Armguards", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather Strips",2), L("Leather",2) ] },
    { id:uid(), name:"Ulfric's Boots", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",2), L("Thread",3) ] },
    { id:uid(), name:"Ulfric's Clothes", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather",1), L("Thread",5) ] },
    { id:uid(), name:"Vaermina Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Vampire Boots", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Vampire Gloves", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Leather",1), L("Thread",1) ] },
    { id:uid(), name:"Vampire Hood", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",2) ] },
    { id:uid(), name:"Vampire Robes", value:null, labor:null, demand:1, src:"keizaal", lines:[ L("Thread",4) ] },
    { id:uid(), name:"Wedding Dress", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",5) ] },
    { id:uid(), name:"Wedding Sandals", value:null, labor:null, demand:1, src:"mod", lines:[ L("Leather Strips",2), L("Leather",1) ] },
    { id:uid(), name:"Wedding Wreath", value:null, labor:null, demand:1, src:"mod", lines:[ L("Thread",1), L("Yellow Mountain Flower",5) ] },
    { id:uid(), name:"Whiterun Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
    { id:uid(), name:"Winterhold Guard Cloak", value:null, labor:null, demand:1, src:"mod", lines:[ L("Linen Wrap",2) ] },
  ],
  };
})();
