"""Fetch the two brand webfaces, subset them to printable ASCII, and emit
fonts.mjs as base64 woff2.

Subsetting matters: every generated SVG inlines these payloads so the sources
open correctly with no network and no locally-installed fonts. Full latin
subsets would add ~90 KB to each of ~35 files; ASCII-only costs a few KB.

    python build-fonts.py
"""
import base64, io, json, re, urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

HERE = Path(__file__).parent
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36")

FACES = {
    "metamorphous":   "https://fonts.googleapis.com/css2?family=Metamorphous",
    "spectralItalic": "https://fonts.googleapis.com/css2?family=Spectral:ital,wght@1,400",
    "spectral":       "https://fonts.googleapis.com/css2?family=Spectral:wght@400",
}

# Printable ASCII covers every string the brand assets set, with room to edit
# copy later without regenerating.
KEEP = list(range(0x20, 0x7F)) + [0x2014, 0x2019, 0x00B7]


def get(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})
    ).read()


out = {}
for key, css_url in FACES.items():
    css = get(css_url).decode("utf-8")
    # The `latin` block is the one whose unicode-range starts at U+0000.
    blocks = css.split("@font-face")[1:]
    latin = next((b for b in blocks if "U+0000-00FF" in b), blocks[-1])
    woff2_url = re.search(r"url\((https:[^)]+\.woff2)\)", latin).group(1)

    raw = get(woff2_url)
    font = TTFont(io.BytesIO(raw))

    sub = subset.Subsetter(options=subset.Options(
        layout_features=["*"], notdef_outline=True, drop_tables=[], hinting=True,
    ))
    sub.populate(unicodes=KEEP)
    sub.subset(font)

    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    small = buf.getvalue()

    out[key] = base64.b64encode(small).decode("ascii")
    print(f"{key:<16} {len(raw)/1024:6.1f} KB -> {len(small)/1024:5.1f} KB subset")

js = (
    "// AUTO-GENERATED by build-fonts.py - do not edit.\n"
    "// Printable-ASCII subsets of the brand faces as base64 woff2, so every\n"
    "// generated SVG is self-contained (no network, no installed fonts).\n"
    f"export const FONTS = {json.dumps(out)};\n"
)
(HERE / "fonts.mjs").write_text(js, encoding="utf-8")
print(f"\nwrote fonts.mjs ({len(js)/1024:.0f} KB)")
